name: KothRewards
main: me.ByteMagic.KothRewards.Main
version: 1.3.2
description: Rewards your players with custom commands after winning a koth.
author: ByteMagic
depend: [KoTH]
softdepend: [Factions]